# Generated by Django 5.1.6 on 2025-10-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_notified",
            field=models.BooleanField(default=False),
        ),
    ]
